name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  reorderable_grid_view: ^2.2.6 
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  provider: ^6.0.5
  fl_chart: ^0.68.0
  animated_text_kit: ^4.2.2
  smooth_page_indicator: ^1.1.0
  flutter_slidable: ^3.0.0
  animations: ^2.0.2
  intl: any
  syncfusion_flutter_charts: ^21.1.0
  adaptive_theme: ^3.6.0 # Aggiungi questa linea
  flutter_localizations: 
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sfondo_tutorial.jpg
    - assets/images/uk_flag.jpg
    - assets/images/it_flag.jpg
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic